import Header from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={"font-sans"}>
				<Header />
				<main className='lg:mx-24 lg:my-8 md:m-16 m-8'>{children}</main>
			</body>
		</html>
	);
}
